# Generated by Django 4.1.7 on 2023-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.DeleteModel(
            name='Player_name',
        ),
    ]
